### ISSUE TITLE
File name for message/rfc822 parts is always message.eml

### ISSUE THREAD

**Issue by petardimitrijevic** [aspineux/pyzmail#2]
Hi,

I've noticed a problem with the names of the files from message/rfc822 parts. Instead of getting the file name from the mail part you are fixing it to message.eml.

The bug is on line 465 in parse.py.

Instead of:
filename='message.eml'
it should be:
filename=get_filename(part)

Cheers,
Petar

**Comment by aspineux** [comment]
I have pushed the fix
I will be available in next 1.0.4
