### ISSUE TITLE
code is not properly translated for python33 with pip on windows

### ISSUE THREAD

**Issue by xiconet** [aspineux/pyzmail#9]
Sir,
Just in case, I tried to put `pyzmail` at work with Python33 rather than the "old" Python27 I usually stick with, on my windows-xpsp3 "box". 
Taking care to use the appropriate `pip` version, I simply run:
 `````cmd
pip install pyzmail
````
from my `C:\Python33\Scripts` folder.
Unfortunately the resulting code, beginning with the `pyzsendmail` script, has *many* errors.

**Comment by aspineux** [comment]
In the main page, in section "Support for Python 3.x", you can see that you must convert the scripts yourself using py2to3.

I'm distributing a pyzsendmail.exe that should do the job on windows, without installing python nor pyzmail.

Hope this help

**Comment by xiconet** [comment]
Sorry, I didn't notice that 2to3 conversion was not "automatic".
